In [1]:
from google.colab import drive
drive.mount("/gdrive", force_remount=True)

Mounted at /gdrive


In [5]:
import numpy as np
import torch
import torch.nn as nn
from sklearn.metrics import accuracy_score

# 데이터 읽기 함수
def load_dataset(file):
  data = np.loadtxt(file)
  print("DATA=",data)
  
  input_features = data[:,0:-1]
  print("X=",input_features)
  
  labels = np.reshape(data[:,-1],(4,1))
  print("Y=",labels)
 
  input_features = torch.tensor(input_features, dtype=torch.float)
  labels = torch.tensor(labels, dtype=torch.float)

  return (input_features, labels)

# 모델 평가 결과 계산을 위해 텐서를 리스트로 변환하는 함수
def tensor2list(input_tensor):
    return input_tensor.cpu().detach().numpy().tolist()

x, y = load_dataset("/gdrive/My Drive/colab/gda/xortrain.txt")

# layer 1 가중치 초기화
# 이곳을 완성하세요.
w1 = torch.randn(2,2,requires_grad = True)
b1 = torch.randn(2,requires_grad = True)
print("\n[Init]\nw1 = {0}".format(tensor2list(w1)))
print("b1 = {0}".format(tensor2list(b1)))

# layer 2 가중치 초기화
# 이곳을 완성하세요.
w2 = torch.randn(2,1,requires_grad=True)
b2 = torch.randn(1, requires_grad=True)
print("w2 = {0}".format(tensor2list(w2)))
print("b2 = {0}\n".format(tensor2list(b2)))

# Activation 함수 설정
sigmoid = nn.Sigmoid()

# 이진분류 크로스엔트로피 비용 함수 설정 
loss_func = torch.nn.BCELoss()

# 옵티마이저 함수 (역전파 알고리즘을 수행할 함수)
optimizer = torch.optim.SGD([w1,b1,w2,b2],lr=0.2)

# 모델 학습
for epoch in range(1001):

    # H(X) 계산: forward 연산
    L2 = sigmoid(torch.add(torch.matmul(x,w1),b1))
    hx = sigmoid(torch.add(torch.matmul(L2,w2),b2))
    # 이곳을 완성하세요.

    # 비용 계산
    cost = loss_func(hx, y)
    # 역전파 수행
    cost.backward()
    optimizer.step()

    # 100 에폭마다 비용 출력
    if epoch % 100 == 0:
        print(epoch, cost.item())

print("\n[Learned]\nw1 = {0}".format(tensor2list(w1)))
print("b1 = {0}".format(tensor2list(b1)))
print("w2 = {0}".format(tensor2list(w2)))
print("b2 = {0}\n".format(tensor2list(b2)))

# 모델 평가
L2 = sigmoid(torch.add(torch.matmul(x,w1),b1))
hx = sigmoid(torch.add(torch.matmul(L2,w2),b2))

# H(X) 계산: forward 연산
# 이곳을 완성사에요.

logits = (hx > 0.5).float()
predicts = tensor2list(logits)
golds = tensor2list(y)

print("\nPRED=",predicts)
print("GOLD=",golds)
print("Accuracy : {0:f}".format(accuracy_score(golds, predicts)))

DATA= [[0. 0. 0.]
 [0. 1. 1.]
 [1. 0. 1.]
 [1. 1. 0.]]
X= [[0. 0.]
 [0. 1.]
 [1. 0.]
 [1. 1.]]
Y= [[0.]
 [1.]
 [1.]
 [0.]]

[Init]
w1 = [[-0.8669320344924927, -0.1669040322303772], [0.3911643326282501, -0.31995701789855957]]
b1 = [0.4444066882133484, -0.445635586977005]
w2 = [[0.07290396094322205], [0.16034471988677979]]
b2 = [-0.279737651348114]

0 0.6976290941238403
100 0.6942026019096375
200 0.48491254448890686
300 0.3673577904701233
400 3.6434495996218175e-05
500 1.788139627478813e-07
600 0.0
700 0.0
800 0.0
900 0.0
1000 0.0

[Learned]
w1 = [[-146.02882385253906, -139.85081481933594], [-132.12814331054688, -97.45033264160156]]
b1 = [18.813508987426758, 184.0377655029297]
w2 = [[-146.9559783935547], [142.04457092285156]]
b2 = [-104.05075073242188]


PRED= [[0.0], [1.0], [1.0], [0.0]]
GOLD= [[0.0], [1.0], [1.0], [0.0]]
Accuracy : 1.000000
